### ISSUE TITLE
Graph API values returns empty

### ISSUE THREAD

**Issue by vineetraikumar** [OfficeDev/Microsoft-Graph-ASPNET-REST-Excel-Donations#7]
Hi,
I have downloaded the source code and after all settings i have done on azure as well where ever required. When i am running this app, values of arrays is empty. Also i have test it from Postman it's same response.

`{
"@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users('guid')/drive/root/children",
"value": [],
}`
In the mean while I am hitting the same API from Graph explorer its return values What will be the cause ??
**I need the functionality to edit/update existing excel file which is stored on one drive**

**Comment by jamescro** [comment]
When you test in the Graph Explorer, are you hitting exactly the same endpoint? The most obvious explanation would be that the two calls are pointing at different locations. Are you able to populate data by using the sample UI?

Also, is it correct to assume that "guid" in the path you mention above is a placeholder for the actual user id?

**Comment by jamescro** [comment]
Closing for now. Please reopen if you continue to see this issue.

**Comment by MrYusifli** [comment]
i am having the same issue... in postman call i am able to get json with information value. but when i am using intellij and restful api for automation i am getting empty value in value part. 
![image](https://user-images.githubusercontent.com/44886556/72554075-37574d80-3857-11ea-9195-7179b7078a1c.png)
any ideas maybe?
