### ISSUE TITLE
Empty value when request root/Children

### ISSUE THREAD

**Issue by armon75226** [OfficeDev/Microsoft-Graph-ASPNET-REST-Excel-Donations#8]
Hi, I did setup oAuth2 for Microsoft Graph.  Everything is working but when I request for list of directories:
https://graph.microsoft.com/v1.0/me/drive/root/children
I get this:
{
    "value": []
}

The location (https://******.sharepoint.com/personal/******/Documents) returns my directories with no issue.
Please help.
Thanks

**Comment by jamescro** [comment]
Have you uploaded the WoodGroveBankExpenseTrendsWorkbook.xlsx file to the root OneDrive directory of your Office 365 tenant? The file would appear at that endpoint if you did.

You can see what is in your root OneDrive at this URL:

https://*****.sharepoint.com/personal/******/_layouts/15/onedrive.aspx

**Comment by armon75226** [comment]
I am not sure what WoodGroveBankExpenseTrendsWorkbook.xlsx file is!!!

**Comment by jamescro** [comment]
It's this file in the root of the repo:

https://github.com/microsoftgraph/aspnet-donations-rest-sample/blob/master/WoodGroveBankExpenseTrendsWorkbook.xlsx

The code in this sample expects to see that Excel workbook in the OneDrive root. It writes data to that file.

**Comment by jamescro** [comment]
Closing for now. Please reopen if your problem persists when you upload the file.
